#!/bin/sh
# Print CPU and GPU temperature
echo "GPU temperature: $(vcgencmd measure_temp | grep -oP '\d+\.\d+') °C"
echo "CPU temperature: $(cat /sys/class/thermal/thermal_zone0/temp | awk '{print $1/1000}') °C"
